### ISSUE TITLE
Home assistant 115.5 error

### ISSUE THREAD

**Issue by samhaa** [anand-p-r/fmi-hass-custom#6] opened 2020-09-30 15:35 UTC
Hi,

Component worked fine with 115.x until 115.5 I got error

Logger: homeassistant.setup
Source: custom_components/fmi/__init__.py:171
First occurred: 12:37:24 PM (1 occurrences)
Last logged: 12:37:24 PM

Error during setup of component fmi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/fmi/__init__.py", line 171, in async_setup
    for index, entity in enumerate(config[DOMAIN], start=0):
KeyError: 'fmi'

**Comment by ojalaj** [comment] 2020-10-02 19:06
Hi. I have faced this error too.

**Comment by anand-p-r** [comment] 2020-10-03 05:51
Hi,

I upgraded to 115.6 just now (offered by the Update component in Supervisor) and did not see the same kind of logs. Can you also try to upgrade and see if you are still facing problems?

Regards,
Anand.

**Comment by ojalaj** [comment] 2020-10-03 06:01
Hi!

Actually I'm on 0.115.6 as well, but have the problem.

**Comment by ojalaj** [comment] 2020-10-03 16:09
When googling lines above I see some similarities in issues other users have experienced with 0.115, but also with older versions, with other add-ons. Unfortunately I can't say what is the actual cause and how to solve it here....

**Comment by samhaa** [comment] 2020-10-04 13:26
Hi,

I tried 115.6 and it didn't work either. Rollbacked to 115.3 as I also had
other problems with 115.5 and 115.6.

**Comment by anand-p-r** [comment] 2020-10-05 15:14
Hi,

Does it now work with the older version?

Regards,
Anand.

**Comment by samhaa** [comment] 2020-10-06 12:39
Hi,

Yes it's working fine with 115.3.

**Comment by ojalaj** [comment] 2020-10-06 18:19
@anand-p-r have you plans to debug why it breaks, when upgrading from 0.115.3--> or is the only solution now to roll back from 0.115.6?

**Comment by anand-p-r** [comment] 2020-10-07 05:52
Hi,
It is hard to say anything without being able to reproduce the problem. I will try few things during this week/weekend and see if I can help. As of now I have this running without issues in 0.115.6
Regards,
Anand.

**Comment by samhaa** [comment] 2020-10-08 16:25
Hi,

0.116.0 works for me.

*-Sami*

**Comment by anand-p-r** [comment] 2020-10-08 18:12
Nice!! I will give it a shot this weekend.

**Comment by ojalaj** [comment] 2020-10-08 19:01
@samhaa Good to hear! I don't dare to upgrade yet to 0.116.0 :).

**Comment by ojalaj** [comment] 2020-10-09 20:21
I upgraded to 0.116.2, but still get the error.

**Comment by anand-p-r** [comment] 2020-10-10 08:59
I can't seem to reproduce any problem with 0.115. I will now upgrade to 0.116.2 and see.

On a side note, can this be due to python version problems. Do you know the version of python in your environment where HASS is running?

**Comment by samhaa** [comment] 2020-10-10 15:27
116.2 works for me.
Hass Python version 3.8.5.

**Comment by anand-p-r** [comment] 2020-10-10 18:53
Works for me too on 116.2.

**Comment by ojalaj** [comment] 2020-10-10 19:18
I won't have access to my HASS.io in couple of days. Do I need to run something on command-line to get Python upgraded? In addition to upgrading HASS, I always have upgraded the core system as well and I have thought that Python would get upgraded as well.

**Comment by ojalaj** [comment] 2020-10-16 20:36
I have now 0.116.4 and it seems that I have Python version 3.8.5.

**Comment by anand-p-r** [comment] 2020-10-19 11:20
I upgraded to 0.116.4 now. No issues seen with the FMI integration.

**Comment by samhaa** [comment] 2020-10-19 14:40
Same here. No issues.

**Comment by anand-p-r** [comment] 2020-10-21 07:06
> I have now 0.116.4 and it seems that I have Python version 3.8.5.

@ojalaj: I just noticed from the original post that the file where error was seen is "init.py". In the latest version, it is "__init__.py". Is it possible that somehow you have been using the older version and that has somehow corrupted the integration in your env?

If you are still having this problems with the integration, can you try these steps and see if it helps:
1. Remove all the FMI configuration from configuration.yaml file. Remove the fmi directory from custom_components. Download the latest version (master) and re-create it under custom_components.
2. Remove all UI references to FMI as well, or else they will show up as "entity not found".
3. Restart HASS and allow everything to come up. Hopefully no FMI related error should be seen if you have cleaned everything as mentioned in steps above.
4. Update configuration.yaml again with FMI weather (and / or sensor), using steps mentioned in the README.md.
5. Restart HASS and cross fingers!

**Comment by ojalaj** [comment] 2020-10-21 19:16
Thanks @anand-p-r for follow-up. I followed the steps, but unfortunately (still) get:

```
Logger: homeassistant.setup
Source: custom_components/fmi/__init__.py:171
First occurred: 22.10.56 (1 occurrences)
Last logged: 22.10.56

Error during setup of component fmi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/fmi/__init__.py", line 171, in async_setup
    for index, entity in enumerate(config[DOMAIN], start=0):
KeyError: 'fmi'
```

Maybe I just need to give up :(

**Comment by vaieant** [comment] 2020-10-31 13:07
I have exactly the same issue as ojalaj. I receive exactly the same error message on the log. I'm on Home Assistant Supervised:

host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_version | 4.19.0-12-amd64
python_version | 3.8.6
supervisor | 2020.10.0
version | 0.117.1

**Comment by anand-p-r** [comment] 2020-11-03 14:36
Hi,
I now have a PR open in homeassistant/core to integrate FMI based weather sensor.
https://github.com/home-assistant/core/pull/42409

It is pending review. If possible some of you folks could review it and hopefully it will be part of the main release soon.

**Comment by anand-p-r** [comment] 2020-11-09 12:12
I have now implemented the config_flow guidelines for the custom component as well. It is available in the latest [commit]( https://github.com/anand-p-r/fmi-hass-custom). Please follow pre-installation instructions to remove old references of the custom component. Do let me know if this solves the problems you had faced earlier.

**Comment by makkeu** [comment] 2020-12-08 21:10
I had the same issue as ojalaj. I tried to reinstall the latest version and add integration from the UI. Integration were found, but I can't enable it. Checked the logs and found this error:

```
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:167 
Integration: Weather (documentation, issues) 
First occurred: 22.54.16 (2 occurrences) 
Last logged: 22.56.20

Error while setting up fmi platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 196, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 167, in async_create_setup_task
    return platform.async_setup_entry(  # type: ignore
AttributeError: module 'custom_components.fmi.weather' has no attribute 'async_setup_entry'
```

**Comment by makkeu** [comment] 2020-12-08 21:22
Ok, found the issue. Somehow copy to samba share failed for one file, it had zero bytes on hassio. Reuploaded it and after the restart this integration started to work. Good work!

**Comment by anand-p-r** [comment] 2020-12-09 09:41
Good to know! and thanks for trying this @makkeu

**Closed by anand-p-r** 2020-12-09 09:41 UTC
